### ISSUE TITLE
Issue in code of face recognition 

### ISSUE THREAD

**Issue by Anurag1201** [emara-geek/real-time-face-detection-using-opencv-with-java#1]
i have followed your instructions in the given video but still it is giving error in Core.Nativelibrary

**Comment by ruturp** [comment]
I have followed your instruction in given video but still it is giving error is below: 
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture; this two package is exsist.
and  Core.**rectangle**(frame, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height),
cannot find rectangle symbol

**Comment by tahaemara** [comment]
in opencv3.0, there is no highgui module in java.
To migrating from OpenCV 2.x to 3.0.0 (Java)

`Highgui.imread(fileName, Highgui.CV_LOAD_IMAGE_GRAYSCALE) `becomes `Imgcodecs.imread(fileName, Imgcodecs.CV_LOAD_IMAGE_GRAYSCALE)`

And `Highgui.imread(fileName)` becomes `Imgcodecs.imread(fileName)`

also , drawing functions such as:

`Core.circle(..),  Core.line(..)` become `Imgproc.circle(..), Imgproc.line(..)`
 `Core.rectangle(frame, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height) `becomes  `Imgproc.rectangle(frame, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height);`

**Comment by catapulveda** [comment]
Hi, Taha! You should publish the facial recognition source code in java. Thank you.

**Comment by alciomarhollanda** [comment]
Hi,

In openCV 3.2 don't work Imgcodecs.imread(".bmp", frame, mem);

![image](https://user-images.githubusercontent.com/5420987/27335458-d9b2bf3c-55a2-11e7-9462-7e68155bf77c.png)

**Comment by Ayush0601** [comment]
if (webSource.grab()) {
 
            System.out.println("err");                     
  try
 {
                        
                          webSource = new VideoCapture(0);  
                          webSource.retrieve(frame);
 
                           Graphics g = jPanel1.getGraphics();

                            faceDetector.detectMultiScale(frame, faceDetections);

                            for (Rect rect : faceDetections.toArray())
 {

                               
                                Imgproc.rectangle(frame, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height),   new Scalar(0, 255,0));

error in this part of code

**Comment by tahaemara** [comment]
Post the error message here, so, I can check it.

**Comment by tahaemara** [comment]
@alciomarhollanda 
Keep in mind that function Imgcodecs.imread takes a parameter represent the path of the image 
Mat image = Imgcodecs.imread(getClass().getResource("/lena.png").getPath());

**Comment by livingstone90** [comment]
I am facing this error

OpenCV Error: Assertion failed (!empty()) in cv::CascadeClassifier::detectMultiScale, file C:\build\master_winpack-bindings-win64-vc14-static\opencv\modules\objdetect\src\cascadedetect.cpp, line 1698
Error

**Comment by tahaemara** [comment]
@livingstone90  
Try to use the absolute path to the cascade file, in other words, try to replace this line 
`CascadeClassifier faceDetector = new CascadeClassifier(FaceDetection.class.getResource("haarcascade_frontalface_alt.xml").getPath().substring(1));`
with 
`CascadeClassifier faceDetector = new CascadeClassifier("/path/to/haarcascade_frontalface_alt.xml");`

**Comment by livingstone90** [comment]
Hi,How can i reduce the size frame of the video capture section..I dont want it to be long from left to right but I want it to align only on left side

**Comment by tahaemara** [comment]
@livingstone90  use these lines to change the size of the frames 
`  capture.set(Highgui.CV_CAP_PROP_FRAME_WIDTH, WIDTH);
    capture.set(Highgui.CV_CAP_PROP_FRAME_HEIGHT, HEIGHT);`

**Comment by trinhngockhang** [comment]
![image](https://user-images.githubusercontent.com/26276956/32320972-3994b7c0-bff2-11e7-9cdc-1b2eb244fd47.png)
I don't know why it's not work,i wait for it running but nothing happen

**Comment by jimiking** [comment]
hi taha.
i want make java app similar your app.
 capture (webcam and ip camera) thin detect face with name .
please
please
please
please

**Comment by tahaemara** [comment]
@jimiking search google about "eigenfaces algorithm with java" you will see a lot of results.
